server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springecommerece
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    host: localhost
    port: 15672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated

jwt:
  HEADER_STRING: Authorization
  tokenPrefix: Bearer
  secretKey: secret
  expirationTimeMinute: 150
logging:
  level:
    #root: ERROR
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE
    com.itsthatjun.ecommerce: DEBUG
queue:
  OMS:
    order: order
    orderComplete: orderComplete
    orderDelayedCancel: orderDelayedCancel
    cart: cart
    return: return
    returnDelayedRejection: returnDelayedRejection
  PMS:
    review: review
  UMS:
    user: user


spring.rabbitmq:
  host: localhost
  port: 5672
  virtual-host: /
  username: guest
  password: guest
  publisher-confirm-type: correlated

---

spring.config.activate.on-profile: docker

spring:
  datasource.url: jdbc:postgresql://localhost:5432/ecommerce
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: springecommerece
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq

spring.rabbitmq.host: rabbitmq